### ISSUE TITLE
ImportError: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found

### ISSUE THREAD

**Issue by monajalal** [eunsol/document-e2e-sent#1]
I get this error running your code:

```
[jalal@goku document-e2e-sent]$ python baseline_model_GPU.py 
Traceback (most recent call last):
  File "baseline_model_GPU.py", line 12, in <module>
    import graph_results as plotter
  File "/scratch2/debate_tweets/sentiment/document-e2e-sent/graph_results.py", line 1, in <module>
    import matplotlib.pyplot as plt
  File "/scratch/sjn/anaconda/lib/python3.6/site-packages/matplotlib/pyplot.py", line 115, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/scratch/sjn/anaconda/lib/python3.6/site-packages/matplotlib/backends/__init__.py", line 62, in pylab_setup
    [backend_name], 0)
  File "/scratch/sjn/anaconda/lib/python3.6/site-packages/matplotlib/backends/backend_qt5agg.py", line 15, in <module>
    from .backend_qt5 import (
  File "/scratch/sjn/anaconda/lib/python3.6/site-packages/matplotlib/backends/backend_qt5.py", line 19, in <module>
    import matplotlib.backends.qt_editor.figureoptions as figureoptions
  File "/scratch/sjn/anaconda/lib/python3.6/site-packages/matplotlib/backends/qt_editor/figureoptions.py", line 20, in <module>
    import matplotlib.backends.qt_editor.formlayout as formlayout
  File "/scratch/sjn/anaconda/lib/python3.6/site-packages/matplotlib/backends/qt_editor/formlayout.py", line 54, in <module>
    from matplotlib.backends.qt_compat import QtGui, QtWidgets, QtCore
  File "/scratch/sjn/anaconda/lib/python3.6/site-packages/matplotlib/backends/qt_compat.py", line 140, in <module>
    from PyQt5 import QtCore, QtGui, QtWidgets
ImportError: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /scratch/sjn/anaconda/lib/python3.6/site-packages/PyQt5/QtCore.so)
[jalal@goku document-e2e-sent]$ 
```

**Comment by monajalal** [comment]
Ran it with Anaconda Python 2.7 and got no error and the following was produced.
![screenshot from 2018-04-20 13-54-52](https://user-images.githubusercontent.com/1892917/39066281-81f08f28-44a2-11e8-960f-dfe2d761aaa9.png)
