### ISSUE TITLE
  File "baseline_model.py", line 278, in main     train_data, dev_data, test_data, TEXT = parser.parse_input_files(BATCH_SIZE, EMBEDDING_DIM) TypeError: parse_input_files() takes exactly 3 arguments (2 given)

### ISSUE THREAD

**Issue by monajalal** [eunsol/document-e2e-sent#3]
So when I run the following I get error. Also, how can I test this on my own tweet data for detecting sentiment of each entity? What should be the format of test data?

```
[jalal@goku document-e2e-sent]$ python baseline_model.py 
Traceback (most recent call last):
  File "baseline_model.py", line 313, in <module>
    main()
  File "baseline_model.py", line 278, in main
    train_data, dev_data, test_data, TEXT = parser.parse_input_files(BATCH_SIZE, EMBEDDING_DIM)
TypeError: parse_input_files() takes exactly 3 arguments (2 given)
```

**Comment by monajalal** [comment]
Ran it with Anaconda Python 2.7 and got no error and the following was produced.
![screenshot from 2018-04-20 13-54-52](https://user-images.githubusercontent.com/1892917/39066281-81f08f28-44a2-11e8-960f-dfe2d761aaa9.png)
