### ISSUE TITLE
IOError: [Errno 2] No such file or directory: './data/new_annot/polarity_label_holdtarg/new_train.json'

### ISSUE THREAD

**Issue by monajalal** [eunsol/document-e2e-sent#4]
Hello
Can you please share your test and train datase?

```
[jalal@goku document-e2e-sent]$ python baseline_model_GPU.py 
creating fields
parsing data from file
Traceback (most recent call last):
  File "baseline_model_GPU.py", line 333, in <module>
    main()
  File "baseline_model_GPU.py", line 295, in main
    train_data, dev_data, test_data, TEXT = parser.parse_input_files(BATCH_SIZE, EMBEDDING_DIM, using_GPU)
  File "/scratch2/debate_tweets/sentiment/document-e2e-sent/data_processor.py", line 47, in parse_input_files
    'holder_target': ('holder_target', HOLDER_TARGET)}
  File "/scratch/sjn-p2/anaconda/anaconda2/lib/python2.7/site-packages/torchtext/data/dataset.py", line 76, in splits
    os.path.join(path, train), **kwargs)
  File "/scratch/sjn-p2/anaconda/anaconda2/lib/python2.7/site-packages/torchtext/data/dataset.py", line 215, in __init__
    with io.open(os.path.expanduser(path), encoding="utf8") as f:
IOError: [Errno 2] No such file or directory: './data/new_annot/polarity_label_holdtarg/new_train.json'
[jalal@goku document-e2e-sent]$ ls ./data/new_annot/polarity_label_holdtarg/
[jalal@goku document-e2e-sent]$ 
```

**Comment by julestree** [comment]
Hello! I would also like to use the test and train datasets.
@monajalal Did you ever find the data?
